#!/usr/bin/env python2.7

import os.path


def _color_func(colorcode):
    def result(s):
        return '\033[{0}m{1}\033[0m'.format(colorcode, s)

    return result


grey = _color_func(30)
red = _color_func(31)
green = _color_func(32)
yellow = _color_func(33)
blue = _color_func(34)
magenta = _color_func(35)
cyan = _color_func(36)
white = _color_func(37)

print os.path.curdir

if __name__ == "__main__":
    for s in ('blue', 'yellow', 'green', 'red', 'cyan', 'magenta'):
        print locals()[s](s)
