#!/usr/bin/env python
from subprocess import call

with open('repos', 'r') as f:
    for line in f:
        path, repo = line.strip().split(', ')
        print "Cloning", repo, "into", path
        call("mkdir -p {0}".format(path), shell=True)
        call("git clone {0} {1}".format(repo, path), shell=True)
        
